apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opp
  namespace: openshift-gitops
spec:
  project: opp
  source:
    repoURL: https://github.com/workshop-opp/opp-gitops.git
    targetRevision: master
    path: opp/base
  destination:
    server: https://kubernetes.default.svc
    namespace: opp
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops