apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: opp
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/workshop-opp/opp-gitops.git
status: {}
