---
kind: Secret
apiVersion: v1
metadata:
  name: htpasswd-opp
  namespace: openshift-config
data:
  htpasswd: >-
    YXRoZW5zLXRlYW06JDJ5JDA1JEZjdThYQWNqaU5lSnV1R2VJdmxSS3V2dFVQWWhCb052c3hMdG1sTE1hNmVlUjU0OUtvTWhXCmJybm8tdGVhbTokMnkkMDUkckkuWUs2ZjloWS5DYUhvMEZldGNOZS93S3guZjQ1aU9GMjZzS2J2eml5Wm43SHgwRTY1WUMKYnJ1c3NlbHMtdGVhbTokMnkkMDUkSWljY2F2alM2Ry5lbjFlOHpSdS8vZWsyLkdJcVA1TWd4bUt6aC5RekFiNEh5cXR2S2wwbTYKYnVjaGFyZXN0LXRlYW06JDJ5JDA1JGQuQnZGcjYwUUFUcFJYOE1wWC5UTi51ZTR5a2RvWmNkZy5FL3BNcjkwUEM3LzQxaC5LeTcuCmR1Ymxpbi10ZWFtOiQyeSQwNSRlbmpSajFSYkRIaHQ3S002RkdPRjl1RXVMTjFOSFdzLzNncU5ramJBTlVvT2xNdWticFM0cQpsaXNib2EtdGVhbTokMnkkMDUkc3U2LlgxNGE3S292REp3SFdkUVBFZW1uem9BVmN3aTdwUGE2YjducFZFVnZGaFBnUXdudy4KbG9uZG9uLXRlYW06JDJ5JDA1JFNvVkhET1ZoU3ZiVFRFV2l1d3RoVHVMQjhsWVNkNktQZzJqZFF1M1dZcEV4QWg1Mkx4YlZhCnBhcmlzLXRlYW06JDJ5JDA1JFlGUEpZckNrNUFUVGlTY1pxeDByMXV6d0FrbVNqazNubG85cUREaVdkamtLeFJrMmxTOUtDCnZhcnNvdmlhLXRlYW06JDJ5JDA1JEVLTVptTzhRbTdsNjN2cEx2OVNCby45bUJNRDVzWnE0ZVkxUFB2NUhHYWIzQkdYTDYub3VTCnN0b2NraG9sbS10ZWFtOiQyeSQwNSRjRHluUDVFWnRCTmFuUXQ5Y2kzWkt1Q1c2MVU2bHN6Q1U2bi9LcFNyVXE2VjVJWVNZVEtTZQo=
type: Opaque
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd-secret
      mappingMethod: claim
      name: htpasswd_provider
      type: HTPasswd
    - htpasswd:
        fileData:
          name: htpasswd-rhte
      mappingMethod: claim
      name: htpasswd_rhte
      type: HTPasswd
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-team
  namespace: opp
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: opp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
