apiVersion: v1
kind: Namespace
metadata:
  name: data-theft
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: jndi-exploit-kit
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: opp
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Advanced Cluster Management for Kubernetes"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: open-cluster-management