apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/pimps/JNDI-Exploit-Kit.git
  labels:
    app: jndi-exploit-kit
    app.kubernetes.io/component: jndi-exploit-kit
    app.kubernetes.io/instance: jndi-exploit-kit
    app.kubernetes.io/name: jndi-exploit-kit
    app.kubernetes.io/part-of: jndi-exploit-kit
  name: jndi-exploit-kit
  namespace: jndi-exploit-kit
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/pimps/JNDI-Exploit-Kit.git
  labels:
    app: jndi-exploit-kit
    app.kubernetes.io/component: jndi-exploit-kit
    app.kubernetes.io/instance: jndi-exploit-kit
    app.kubernetes.io/name: jndi-exploit-kit
    app.kubernetes.io/part-of: jndi-exploit-kit
  name: jndi-exploit-kit
  namespace: jndi-exploit-kit
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: jndi-exploit-kit:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM docker.io/library/openjdk:11
      RUN curl -Lo /home/jboss/JNDI-Exploit-Kit-1.0-SNAPSHOT-all.jar https://github.com/pimps/JNDI-Exploit-Kit/raw/master/target/JNDI-Exploit-Kit-1.0-SNAPSHOT-all.jar
      ENTRYPOINT [ "java", "-jar", "/home/jboss/JNDI-Exploit-Kit-1.0-SNAPSHOT-all.jar" ]
      CMD [ "-C", "TODO", "-J", "jndi-exploit-kit.jndi-exploit-kit.svc:8080", "-L", "jndi-exploit-kit.jndi-exploit-kit.svc:1389", "-R", "jndi-exploit-kit.jndi-exploit-kit.svc:1099" ]
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: java-runtime:openjdk-11-ubi8
        namespace: openshift
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: "false"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"jndi-exploit-kit:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"jndi-exploit-kit\")].image","pause":"false"}]'
    app.openshift.io/vcs-uri: https://github.com/pimps/JNDI-Exploit-Kit.git
  labels:
    app: jndi-exploit-kit
    app.kubernetes.io/component: jndi-exploit-kit
    app.kubernetes.io/instance: jndi-exploit-kit
  name: jndi-exploit-kit
  namespace: jndi-exploit-kit
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: jndi-exploit-kit
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: jndi-exploit-kit
    spec:
      containers:
      - image: jndi-exploit-kit:latest
        imagePullPolicy: Always
        name: jndi-exploit-kit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jndi-exploit-kit
  name: jndi-exploit-kit
  namespace: jndi-exploit-kit
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: ldap
    port: 1389
    protocol: TCP
    targetPort: 1389
  - name: rmi
    port: 1099
    protocol: TCP
    targetPort: 1099
  selector:
    deployment: jndi-exploit-kit
  sessionAffinity: None
  type: ClusterIP
