apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/workshop-opp/visa-processor.git
  labels:
    app: visa-processor
    app.kubernetes.io/component: visa-processor
    app.kubernetes.io/instance: visa-processor
    app.kubernetes.io/name: visa-processor
    app.kubernetes.io/part-of: visa-processor
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.18-ubi9
  name: visa-processor
  namespace: data-theft
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/workshop-opp/visa-processor.git
  labels:
    app: visa-processor
    app.kubernetes.io/component: visa-processor
    app.kubernetes.io/instance: visa-processor
    app.kubernetes.io/name: visa-processor
    app.kubernetes.io/part-of: visa-processor
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.18-ubi9
  name: visa-processor
  namespace: data-theft
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: visa-processor:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/workshop-opp/visa-processor.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang:1.18-ubi9
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: visa-processor
    app.kubernetes.io/component: visa-processor
    app.kubernetes.io/instance: visa-processor
    app.kubernetes.io/name: visa-processor
    app.kubernetes.io/part-of: visa-processor
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.18-ubi9
  name: aws-credentials
  namespace: data-theft
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "Easy, peasy!"
  AWS_SECRET_ACCESS_KEY: "Catch me if you can!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: "false"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"visa-processor:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"visa-processor\")].image","pause":"false"}]'
    app.openshift.io/vcs-uri: https://github.com/workshop-opp/visa-processor.git
  labels:
    app: visa-processor
    app.kubernetes.io/component: visa-processor
    app.kubernetes.io/instance: visa-processor
    app.kubernetes.io/name: visa-processor
    app.kubernetes.io/part-of: visa-processor
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.18-ubi9
  name: visa-processor
  namespace: data-theft
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: visa-processor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: visa-processor
        deployment: visa-processor
    spec:
      containers:
      - image: visa-processor:latest
        imagePullPolicy: IfNotPresent
        name: visa-processor
        env:
        - name: APP_ID
          value: visa-processor
        envFrom:
          secretRef:
            name: aws-credentials
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visa-processor
    app.kubernetes.io/component: visa-processor
    app.kubernetes.io/instance: visa-processor
    app.kubernetes.io/name: visa-processor
    app.kubernetes.io/part-of: visa-processor
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.18-ubi9
  name: visa-processor
  namespace: data-theft
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: visa-processor
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: visa-processor
    app.kubernetes.io/component: visa-processor
    app.kubernetes.io/instance: visa-processor
    app.kubernetes.io/name: visa-processor
    app.kubernetes.io/part-of: visa-processor
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: 1.18-ubi9
  name: visa-processor
  namespace: data-theft
spec:
  host: visa-processor.{{ .Values.openshiftDnsZone }}
  tls:
    termination: edge
  to:
    kind: Service
    name: visa-processor
    weight: 100
  wildcardPolicy: None